### ISSUE TITLE
vendor dependencies

### ISSUE THREAD

**Issue by mattetti** [gomidi/smfimage#2]
I'd suggest to vendor the dependencies to make it easier to install/run. Also note that `github.com/metakeule/config` is missing in the README

**Comment by metakeule** [comment]
@mattetti

Thanks for trying. I'll wait for Go 1.11 to include vgo and then revamp lots of my packages
after having figured, if vendoring keeps making sense for me.

**Comment by metakeule** [comment]
now working with go modules, therefor closing
